<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.6.0</Version>
    <Product>RemoteAccessHub</Product>
    <Company>Personal</Company>
    <Copyright>Personal use</Copyright>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <Deterministic>true</Deterministic>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>
</Project>
